### ISSUE TITLE
s3 bucket for images per staging env

### ISSUE THREAD

**Issue by wouterd** [part-up/staging-envs#1]

**Comment by Krijger** [comment]
- [ ] create Jenkins user in AWS (IAM)
- [ ] create Access Key for Jenkins user
- [ ] create s3 bucket when an environment is created using Amazon CLI/API (from Jenkins)
- [ ] configure Meteor to use that bucket

**Comment by Krijger** [comment]
To create a staging environment using a branch of staging-envs, run a manual build in [Jenkins](https://jenkins.part-up.com/job/Deploy%20or%20Refresh%20a%20staging%20environment/build?delay=0sec) specifying the GIT_BRANCH to the branch (e.g. separate-w3-buckets). This will set the PARTUP_BRANCH to the same value.

**Comment by Krijger** [comment]
The following output for the Jenkins `cleanup unneeded stacks` job proves that the code changes for the fourth implementation point of this story work:

    Checking stack stg-separate-w3-buckets
    Checking for branch 'separate-w3-buckets' in repos..
    Branch separate-w3-buckets exists for staging-envs repo, not removing stack...
    Checking stack stg-ft-remove-me
    Checking for branch 'ft-remove-me' in repos..
    Removing stack stg-ft-remove-me, because no single repo has the branch ft-remove-me...

**Comment by Krijger** [comment]
Links with information needed to create the bucket
- [authentication](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html)
- [s3 REST API](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html)

**Comment by wouterd** [comment]
could just use the amazon CLI. Should make things somewhat easier.

**Comment by Krijger** [comment]
Access policy has been created and tested for the Jenkins user:

> ➜  Desktop aws s3 mb s3://test-bucket
> make_bucket failed: s3://test-bucket/ A client error (AccessDenied) occurred when calling the CreateBucket operation: Access Denied
> 
> ➜  Desktop aws s3 mb s3://test-bucket.images.part-up.com
> make_bucket: s3://test-bucket.images.part-up.com/
> 
> ➜  Desktop aws s3 rb s3://test-bucket.images.part-up.com
> remove_bucket: s3://test-bucket.images.part-up.com/

**Comment by Krijger** [comment]
AWS Access information available in slave under environment variables

    AWS_ACCESS_KEY
    AWS_ACCESS_SECRET

**Comment by Krijger** [comment]
```
Make sure an S3 bucket is dedicated to the staging environment
Creating bucket s3://separate-s3-buckets.images.part-up.com
make_bucket: s3://separate-s3-buckets.images.part-up.com/
Generating docker-compose file...
Creating new stack..
In progress......
Success
87960f61-11f8-4369-b22a-7fb7a2c6032d
Updating HAProxy...
Linking stg-develop
```

**Comment by Krijger** [comment]
@wouterd Everything works and the stacks are being redeployed as I write. After they are working, we can delete the partup-development bucket, right?

**Comment by wouterd** [comment]
Don't delete the bucket. It's in use.

**Comment by wouterd** [comment]
Done!
